function answerQuestion() {
    const question = document.getElementById("question").value.toLowerCase();
    const answer = document.getElementById("answer");

    if (question.includes("presumption of innocence")) {
        answer.innerHTML =
            "Presumption of innocence means that every person is considered innocent until proven guilty by a court of law.";
    } else if (question.includes("contract")) {
        answer.innerHTML =
            "A contract is a legally binding agreement between two or more parties.";
    } else if (question.includes("crime")) {
        answer.innerHTML =
            "A crime is an act that violates the law and may be punished by the state.";
    } else if (question.trim() === "") {
        answer.innerHTML =
            "Please enter a legal question.";
    } else {
        answer.innerHTML =
            "This educational demo contains only a few example legal concepts. In a real AI assistant, this response would be generated by an AI model.";
    }
}
